#!/usr/bin/env bash
set -e

printf '\nRunning Post Checkout Hook\n'
prevHEAD=$1
newHEAD=$2
checkoutType=$3

echo '    prev HEAD: '"$(git name-rev --name-only "${prevHEAD}")"
echo '     new HEAD: '"$(git name-rev --name-only "${newHEAD}")"

if [[ -r ~/.bash_profile ]]; then
    source ~/.bash_profile
fi

composer=$(which composer)
npm=$(which npm)
nvm=$(which nvm)
echo "composer: ${composer} npm: ${npm} nvm: ${nvm}"

if [[ "${checkoutType}" -eq 1 ]]; then
    # composer path
    if [[ -d ./php-app ]]; then
        path = './php-app'
    else
        path = '.'
    fi

    if [[ -r "${path}/composer.lock" ]]; then
        DIFF="$(git diff --shortstat ${prevHEAD}..${newHEAD} ${path}/composer.lock)"

        if [[ -n $DIFF ]]; then
            $("${composer} clear-cache")
            $("${composer} validate")
            $("${composer} install -o")
        fi
    fi
fi

# Linting
docker run --rm --entrypoint sh -v "$(pwd):/mnt" koalaman/shellcheck-alpine -c 'for file in $(find /mnt -type f -name "*.sh"); do shellcheck --format=gcc $file; done'
docker run --rm -v "$(pwd):/yaml" sdesbure/yamllint yamllint -f parsable .

if [[ -f './Dockerfile' ]]; then
	docker run -i --rm hadolint/hadolint < Dockerfile
fi
