#! /bin/bash

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
FILES=$(git diff --name-only --diff-filter=ACMR develop ${CURRENT_BRANCH})
phpcs=$(which phpcs)
phpmd=$(which phpmd)


# Run phpcs on changed files
if [ -f $phpcs ]; then
	$phpcs --standard=PSR2 ${FILES}
fi

# Run phpmd on changed files
if [ -f $phpmd ]; then
	for i in ${FILES}; do
		$phpmd $i text unusedcode,cleancode,codesize,design,naming
	done
fi

# Docker related commands
if [ -f Dockerfile ]; then
	if [ -f .hadolint.yaml ]; then
		docker run -iv "${pwd}"/.hadolint.yaml:/.hadolint.yaml hadolint/hadolint < ./Dockerfile
	else
		docker run -i hadolint/hadolint < ./Dockerfile
	fi
fi
if [ -f docker-compose.yml ]; then
	docker-compose config -q
fi

# Linting
docker run --rm --entrypoint sh -v "$(pwd):/mnt" koalaman/shellcheck-alpine -c 'for file in $(find /mnt -type f -name "*.sh"); do shellcheck --format=gcc $file; done'
docker run --rm -v "$(pwd):/yaml" sdesbure/yamllint yamllint -f parsable .

if [[ -f './Dockerfile' ]]; then
	docker run -i --rm hadolint/hadolint < Dockerfile
fi
